config/routes.rb
Emagazineweb::Application.routes.draw do

  resources :media_info_collections, :controller => 'media_info_collection' do
    resources :media_info
  end

  resources :media

  root :to => "home#index"

end

app/models/media.rb
class Media < ActiveRecord::Base
	has_attached_file :cover, :styles => { :medium => "300x300>", :thumb => "100x100>" }
end

app/models/media_info.rb
class MediaInfo < ActiveRecord::Base
	has_attached_file :view, :styles => { :thumb  => ["100x100>", :png] }
      # :large  => ["768x1024>", :png],
      # :medium => ["350x470>", :png],

  belongs_to :media_info_collection

end

app/models/media_info_collection.rb
class MediaInfoCollection < ActiveRecord::Base
	has_attached_file :source, :styles => {
	    :large  => ["768x1024>", :png],
	    :medium => ["350x470>", :png],
	    :thumb  => ["100x100>", :png] }

  has_many :media_infos, :dependent => :destroy
  
end

app/models/media_info_collection_observer.rb
require "converter"
include Converter, Converter::Adapters, Converter::Strategies

class MediaInfoCollectionObserver < ActiveRecord::Observer

  def after_save(media_info_collection)
    Rails.logger.debug "media #{media_info_collection.id} saved"
    
    # don't do post-processing if the media_infos are already there
    return unless media_info_collection.media_infos.length == 0
    
    # get a converter and run it
    convert = ConvertBuilder.create(
      SimpleSourceAdapter.new(media_info_collection.source.path),
      MediaInfoDestinationAdapter.new(media_info_collection, "#{File.dirname(media_info_collection.source.path)}/page.jpg"),
      SimpleConvertStrategy.new)
    convert.run
  end

end

app/models/media_info_destination_adapter.rb
require "converter"
include Converter, Converter::Adapters, Converter::Strategies

class MediaInfoDestinationAdapter < DestinationAdapter
  
  def initialize(media_info_collection, file_out)
    Rails.logger.debug "MediaInfoDestinationAdapter.initialize [#{media_info_collection}][#{file_out}]"
    
    @media_info_collection = media_info_collection
    @file_out = file_out
  end
  
  def complete(file_array)
    Rails.logger.debug "MediaInfoDestinationAdapter.complete [#{file_array}]"
    
    # create the MediaInfo bound to the MediaInfoCollection
    file_array.each do |file|
      media_info = MediaInfo.new
      media_info.page_number = file[/-[0-9]+\./][/[0-9]+/]
      media_info.view = File.new(file)
      media_info.media_info_collection = @media_info_collection
      media_info.save
    end
    
    Rails.logger.debug "MediaInfoDestinationAdapter.complete: done"
    
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

end

app/controllers/media_controller.rb
class MediaController < ApplicationController
  def index
  end

  def show
  end

  def new
    @media = Media.new
  end

  def create
    @media = Media.create( params[:media] )
  end

  def edit
  end

  def update
  end

  def destroy
  end

end

app/controllers/media_info_collection_controller.rb
class MediaInfoCollectionController < ApplicationController  
  def index
    @media_info_collections = MediaInfoCollection.order("created_at DESC")
    
    respond_to do |format|
      format.html # index.html.erb
      format.xml # { render :xml => @media_info_collections }
    end

  end

  def show
    @media_info_collection = MediaInfoCollection.find( params[:id] )
    @media_infos = @media_info_collection.media_infos.order("page_number")
    
    respond_to do |format|
      format.html # show.html.erb
      format.xml # show.xml.builder
    end
  end

  def new
    @media_info_collection = MediaInfoCollection.new
  end

  def create
    @media_info_collection = MediaInfoCollection.create( params[:media_info_collection] )
  end

  def edit
  end

  def update
  end

  def destroy
    @media_info_collection = MediaInfoCollection.find( params[:id] )
    @media_info_collection.destroy
    
    respond_to do |format|
      format.html { redirect_to media_info_collections_url }
      format.xml  { head :ok }
    end
  end

end

app/controllers/media_info_controller.rb
class MediaInfoController < ApplicationController
  def index
    @media_info_collection = MediaInfoCollection.find(params[:media_info_collection_id])
    
    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @media_info_collection.media_infos }
    end
  end

  def show
  end

  def new
  end

  def create
  end

  def edit
  end

  def update
  end

  def destroy
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/media_helper.rb
module MediaHelper
end

app/helpers/media_info_collection_helper.rb
module MediaInfoCollectionHelper
end

app/helpers/media_info_helper.rb
module MediaInfoHelper
end

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Emagazineweb</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/media/create.html.erb
<h1>Media#create</h1>
<p>Find me in app/views/media/create.html.erb</p>

app/views/media/destroy.html.erb
<h1>Media#destroy</h1>
<p>Find me in app/views/media/destroy.html.erb</p>

app/views/media/edit.html.erb
<h1>Media#edit</h1>
<p>Find me in app/views/media/edit.html.erb</p>

app/views/media/index.html.erb
<h1>Media#index</h1>
<p>Find me in app/views/media/index.html.erb</p>

app/views/media/new.html.erb
<h1>Media#new</h1>
<p>Find me in app/views/media/new.html.erb</p>
<%= form_for(@media, :as => :media, :html => { :multipart => true }) do |form| %>
  <%= form.file_field :cover %>
  <%= form.submit %>
<% end %>

app/views/media/show.html.erb
<h1>Media#show</h1>
<p>Find me in app/views/media/show.html.erb</p>

app/views/media/update.html.erb
<h1>Media#update</h1>
<p>Find me in app/views/media/update.html.erb</p>

app/views/media_info/create.html.erb
<h1>MediaInfo#create</h1>
<p>Find me in app/views/media_info/create.html.erb</p>

app/views/media_info/destroy.html.erb
<h1>MediaInfo#destroy</h1>
<p>Find me in app/views/media_info/destroy.html.erb</p>

app/views/media_info/edit.html.erb
<h1>MediaInfo#edit</h1>
<p>Find me in app/views/media_info/edit.html.erb</p>

app/views/media_info/index.html.erb
<h1>MediaInfo#index</h1>
<p>Find me in app/views/media_info/index.html.erb</p>

app/views/media_info/new.html.erb
<h1>MediaInfo#new</h1>
<p>Find me in app/views/media_info/new.html.erb</p>

app/views/media_info/show.html.erb
<h1>MediaInfo#show</h1>
<p>Find me in app/views/media_info/show.html.erb</p>

app/views/media_info/update.html.erb
<h1>MediaInfo#update</h1>
<p>Find me in app/views/media_info/update.html.erb</p>

app/views/media_info_collection/create.html.erb
<h1>MediaInfoCollection#create</h1>
<p>Find me in app/views/media_info_collection/create.html.erb</p>

app/views/media_info_collection/destroy.html.erb
<h1>MediaInfoCollection#destroy</h1>
<p>Find me in app/views/media_info_collection/destroy.html.erb</p>

app/views/media_info_collection/edit.html.erb
<h1>MediaInfoCollection#edit</h1>
<p>Find me in app/views/media_info_collection/edit.html.erb</p>

app/views/media_info_collection/index.html.erb
<h1>Media Info Collections</h1>

<% @media_info_collections.each do |media_info_collection| %>
<div>
  <%= link_to media_info_collection.title, media_info_collection_url(media_info_collection.id) %><br/>
  <%= image_tag media_info_collection.source.url(:thumb) %><br/>
</div>
<div class="actions">
  <%= link_to 'delete', media_info_collection, :confirm => 'Are you sure?', :method => :delete %>
</div>
<% end %>

app/views/media_info_collection/new.html.erb
<h1>Media Info Collection</h1>

<%= form_for (@media_info_collection, :html => { :multipart => true }) do |form| %>
<div class="field">
  <%= form.label :title %><br/>
  <%= form.text_field :title %>
</div>
<div class="field">
  <%= form.label :source %><br/>
  <%= form.file_field :source %>
</div>
<div class="actions">
  <%= form.submit %>
</div>
<% end %>

app/views/media_info_collection/show.html.erb
<h1>Media Info Collection</h1>

<% @media_infos.each do |media_info| %>
  <%= image_tag media_info.view.url(:thumb) %>
<% end %>

app/views/media_info_collection/update.html.erb
<h1>MediaInfoCollection#update</h1>
<p>Find me in app/views/media_info_collection/update.html.erb</p>